### ISSUE TITLE
Deprecate `mock-yeah` npm package

### ISSUE THREAD

**Issue by therynamo** [ryanricard/mockyeah#10]
We should note that `mock-yeah` npm package is no longer used, in favor of `mockyeah`.

**Comment by ryanricard** [comment]
I agree. There should already be a NPM depreciation notice upon download of 'mock-yeah'. What additional steps do you think we should take? Add a note to the README?

**Comment by therynamo** [comment]
Yeah. When looking at the `mock-yeah` package on npm,  it isn't clear that I am not suppose to use it in favor of `mockyeah`. 

Some indication of that would helpful.

**Comment by ryanricard** [comment]
- Updated 0.8.x readme to direct npm search traffic to `mockyeah` from `mock-yeah`. Viewable at: https://www.npmjs.com/package/mock-yeah
- Added deprecation notice on `mock-yeah`
  ```shell
  npm deprecate mock-yeah@"<=0.8.1" "WARNING: This project has been renamed to mockyeah. 
  Install using mockyeah instead."
  ```

To my knowledge this is all that can be done. Let this be a lesson, do not rename your packages after publish 😢
