### ISSUE TITLE
Let overwrite behaviour during test run / enable default setups

### ISSUE THREAD

**Issue by mathume** [ryanricard/mockyeah#20]
1.) I have a default test setup with .get(/someRoute/, {json:someResponse1})
2.) alternative test starts
3.) alternative test sets .get(/someRoute/, {json:someResponse2})
4.) test requests /someRoute/
==> mockyeah returns someResponse1
Expected => mockyeah returns someResponse2

Note:
I don't want to run a mockyeah.reset as I have a full workflow I want to test

**Comment by ryanricard** [comment]
Hey, @mathume. Are both `/someRoute/` end points for the exact same route? e.g.:
```js
// default test
mockyeah.get('/animals', { json: [...] })

// alternative test
mockyeah.get('/animals', { json: [...] })
```
...if so, you can only bind a single response per unique end point. Are you passing varying params to each? Do you have a concrete example?

**Comment by mathume** [comment]
Hey @ryanricard 
I understand I would need to unregister (given by RouteResolver) any route I previously registered before registering again.

The use case is simple:
a.) Suppose you have an API:
/login => returns a session token or 401
/details => returns user details, e.g. username "Fred"
b.) I have a default setup
post(/login/, {json:'{"token": "abc-def"}'});
post(/details/, {json:'{"username":"Fred"}'});
c.) I run a test, check username==Fred => test passes
d.) in another test I want the username to be "Pete" BUT I don't want to define the setup b.) again, only "overwrite" the response post(/details/, {json:'{"username":"Pete"}'}); and test that new value after calling the API.

AT:
Background: mockyeah has a default setup
Given there's an api that opens a user session success fully at /login
And the same api gives me details at /details where my username is "Fred"

Scenario: I want a single test to use the username "Pete"
Given background has been set up
When I set the mockyeah to return "Pete" at /details
Then my test is run with "Pete" instead of "Fred"

A good thing would be to have the following code:

var detailsPath = /details/;
var detailsResponse1 = {username:"Fred"}
mockyeah.get(detailsPath, {json:JSON.stringify(detailsResponse1)});

it('should return an overwritten value', function(){
   mockyeah.unregister_get(detailsPath);
   var detailsResponse2 = {username:"Pete"}
   mockyeah.get(detailsPath, {json:JSON.stringify(detailsResponse2)});
   expect(responseFrom("/details")).to.eventually.have.property("username").equal.to("Pete");
}

...or just remove any routes for path detailsPath when calling mockyeah.get before delegating to the RouteResolver.register

Not sure I've explained well :-/

**Comment by ryanricard** [comment]
In this instance, if I am understanding you correctly, `/login` remains unchanged so you don't want to have to re-register it with each test. You simply want to swap the response for a specific route, in this case `/details`.

Given your use case, I would take the approach below. But I can see the need/want to replace a specific route response; and I can see you expecting `.get('/details', {...})` to overwrite the previous route. Unfortunately, this is not how it is currently implemented. The second `.get()` registers an Express route which is never reached because a route higher in the routing precedence order is matched, therefor it is never reached because the previous route responds. I think this is an issue we should solve. Good catch!

```js
describe('User details', function() {
  beforeEach(() => {
    mockyeah.get('/login', { json: {
      token: 'abc'
    }});
  });

  afterEach(() => mockyeah.reset());

  test('first test', function() {
    mockyeah.get('/details', { json: {
      username: 'Fred'
    }});
    ...
  });

  test('second test', function() {
    mockyeah.get('/details', { json: {
      username: 'Pete'
    }});
    ...
  });
});
```

**Comment by mathume** [comment]
Hi, please check out my pull request. Not sure you'd like it. #21

**Comment by therynamo** [comment]
Closed with #22

**Comment by ryanricard** [comment]
@mathume fix available with mockyeah version [v0.15.0 ](https://github.com/ryanricard/mockyeah/tree/v0.15.0)

**Comment by mathume** [comment]
Great!!! Just saw it on npm. Just what I need!!!

**Comment by ryanricard** [comment]
@mathume, awesome. Glad to hear.
