### ISSUE TITLE
Make compatible with older versions of Node

### ISSUE THREAD

**Issue by ryanricard** [ryanricard/mockyeah#26]
mockyeah's use of latest ECMAScript features make incompatible with older versions of node. We should consider increasing its compatibility so more people can benefit from its use.

Done when:
- A minimum Node version is determined.
- CI automation is implemented to assert compatibility with multiple Node versions (e.g. https://github.com/victorbjelkholm/autochecker)
- mockyeah is updated to support the lowest agreed upon version of Node.

**Comment by AndersDJohnson** [comment]
Could transpile with Webpack and use `babel-preset-env`.

**Comment by ryanricard** [comment]
With pr https://github.com/ryanricard/mockyeah/pull/53, Travis CI configuration has been updated to execute automation against the latest version of the following respective versions of Node: 8, 6, and 4. This should accomplish this issue for now. Feel free add to this thread if you believe there is more that should be done to support older versions of Node.
