### ISSUE TITLE
Suggestion: add request journal

### ISSUE THREAD

**Issue by mathume** [ryanricard/mockyeah#28]
It's just a suggestions to add features to this great library.

In hermetic ui testing (as defined by [google](https://testing.googleblog.com/2015/03/android-ui-automated-testing.html)) we mock out backend, considering the front end a system by itself. System level testing would then correspond to e.g. clicking, responding with mockyeah, but also verifying the sent request as is possible for example in [wiremock](http://wiremock.org/docs/verifying/).

Feature: request verification
As a front developer I want to verify the requests sent by my application in order to have system test coverage
Scenario: my application composes a complex request
Given I automate my UI test with selenium
And I choose various options at the UI for a complex request
And I mock out back end with mockyeah (from my selenium / protractor code)
When I confirm my changes
Then I can obtain the sent request from mockyeah
And verify the request is as I expect

Typically, it's important to
- configure if request journal is active or not in order to avoid memory problems in soak testing
- reset the request journal to only check over requests of a certain test run

**Comment by ryanricard** [comment]
@mathume let me know what you think of https://github.com/ryanricard/mockyeah/pull/29. The included test should provide you an understanding of the proposed api.

cc: @therynamo

**Comment by ryanricard** [comment]
Request journaling added with v0.15.2: https://github.com/ryanricard/mockyeah#mockyeah-configuration. Hope this helps.
