### ISSUE TITLE
Support error message in responses with status != 500

### ISSUE THREAD

**Issue by mathume** [ryanricard/mockyeah#32]
By test example
`mockyeah.get('/wondrous', { status: 422 });` will return a response with code 422.
However, when I set
`mockyeah.get('/wondrous', { status: 422, message: "MYERRORCODE" });` mockyeah won't start.
Error message:
Error: Response option(s) invalid. Options must include one of the following: fixture, filePath, html, json, text, status, headers, raw, latency, type
    at validateResponse (/home/sebastian/legolas/frontend/node_modules/mockyeah/app/lib/RouteResolver.js:42:11)

Our backend will return 422 but with several error codes in the field `message`. Therefore for us at least, it is necessary to be able to define this field

**Comment by ryanricard** [comment]
Are you expecting `message` to be a property in a JSON response? i.e.
```js
mockyeah.get('/wondrous', { status: 422, json: { message: "MYERRORCODE" }});
```

**Comment by mathume** [comment]
Thanks, it worked! (blush)
