### ISSUE TITLE
Deactivate log in config

### ISSUE THREAD

**Issue by mathume** [ryanricard/mockyeah#33]
When using mockyeah directly in tests the test runner stdout will always contain the log messages, e.g.
```
Scenario: Make something after logging in
[mockyeah][REQUEST][GET] /wp-json/wp/v2/something (1ms)
[mockyeah][REQUEST][POST] /api/users/401/session (1ms)
      ✓ Given: I logged in (384ms)
```

While this is very helpful during test development, for test reporting it introduces noise and makes the test results hard to read.

We'd like to write test code like
```
var mockyeah = require('mockyeah');
mockyeah.log = false;
mockyeah.get(/wp-json\/wp\/v2\/something/, { json: '{ "info":"something"}'});
```
and in case we have problems while implementing a test we simply change to `mockyeah.log = true;`

**Comment by ryanricard** [comment]
Since you closed this issue, I will assume changes included in release [v0.15.2](https://github.com/ryanricard/mockyeah/blob/master/CHANGELOG.md#0152---2016-11-18) accomplish your needs.
