### ISSUE TITLE
Attaching mocks with different methods to same route shouldn't deregister mocks with non matchig method

### ISSUE THREAD

**Issue by mprokopowicz** [ryanricard/mockyeah#42]
For now it is not possible to write such code in tests:

```
srv.delete('/rules', {status: 204});
srv.post('/rules', {status: 201});
```

because attaching to same path for the second time will unregister all routes with same path, ignoring method

**Comment by ryanricard** [comment]
@mprokopowicz, cleaning up stale issues. This was solved a few months back with your pr https://github.com/ryanricard/mockyeah/pull/41.
